
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.server.xmlflexcup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IGUAL = 14;
  public static final int ACCION = 3;
  public static final int ETIQUETAS = 7;
  public static final int ACCIONES = 2;
  public static final int ETIQUETA = 8;
  public static final int MEN = 16;
  public static final int STRING = 13;
  public static final int NOMBRE = 4;
  public static final int EOF = 0;
  public static final int PARAMETROS = 5;
  public static final int CIERRE = 17;
  public static final int ATRIBUTOS = 9;
  public static final int TEXTO = 11;
  public static final int error = 1;
  public static final int ATRIBUTO = 10;
  public static final int MAY = 15;
  public static final int PARAMETRO = 6;
  public static final int VALOR = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ACCIONES",
  "ACCION",
  "NOMBRE",
  "PARAMETROS",
  "PARAMETRO",
  "ETIQUETAS",
  "ETIQUETA",
  "ATRIBUTOS",
  "ATRIBUTO",
  "TEXTO",
  "VALOR",
  "STRING",
  "IGUAL",
  "MAY",
  "MEN",
  "CIERRE"
  };
}

